// <auto-generated />
using System;
using LOM.API.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LOM.API.Migrations
{
    [DbContext(typeof(LOMContext))]
    partial class LOMContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("LOM.Shared.Models.Cohort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cohorts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            StartDate = new DateTime(2025, 3, 24, 20, 54, 18, 941, DateTimeKind.Local).AddTicks(1036)
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            StartDate = new DateTime(2026, 3, 24, 20, 54, 18, 941, DateTimeKind.Local).AddTicks(1089)
                        },
                        new
                        {
                            Id = 3,
                            IsActive = false,
                            StartDate = new DateTime(2027, 3, 24, 20, 54, 18, 941, DateTimeKind.Local).AddTicks(1093)
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            StartDate = new DateTime(2024, 3, 24, 20, 54, 18, 941, DateTimeKind.Local).AddTicks(1095)
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            StartDate = new DateTime(2023, 3, 24, 20, 54, 18, 941, DateTimeKind.Local).AddTicks(1097)
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            StartDate = new DateTime(2022, 3, 24, 20, 54, 18, 941, DateTimeKind.Local).AddTicks(1100)
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            StartDate = new DateTime(2021, 3, 24, 20, 54, 18, 941, DateTimeKind.Local).AddTicks(1102)
                        });
                });

            modelBuilder.Entity("LOM.Shared.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
