export const dummyApiResponse2 = {
    id: 1,
    name: "Nieuwe Leerroute",
    Semesters: [
        {
            Id: 600000,
            Year: 1,
            semester: 1,
            Module: {
                Id: 200000,
                Name: "Selecteer je module",
                description: "Selecteer je module",
            },
            locked: false,
            Description: `2027-01-01T00:00:00Z`,
        },
        {
            Id: 500000,
            Year: 1,
            semester: 2,
            Module: {
                Id: 300000,
                Name: "Selecteer je module",
                Description: "Selecteer je module",
            },
            locked: false,
            startDate: `2027-10-07T00:00:00Z`,
        },
        {
            Id: 600000,
            Year: 2,
            semester: 1,
            Module: {
                Id: 200000,
                Name: "Selecteer je module",
                description: "Selecteer je module",
            },
            locked: false,
            Description: `2027-01-01T00:00:00Z`,
        },
        {
            Id: 500000,
            Year: 2,
            semester: 2,
            Module: {
                Id: 300000,
                Name: "Selecteer je module",
                Description: "Selecteer je module",
            },
            locked: false,
            startDate: `2027-10-07T00:00:00Z`,
        },
        {
            Id: 600000,
            Year: 3,
            semester: 1,
            Module: {
                Id: 200000,
                Name: "Selecteer je module",
                description: "Selecteer je module",
            },
            locked: false,
            Description: `2027-01-01T00:00:00Z`,
        },
        {
            Id: 500000,
            Year: 3,
            semester: 2,
            Module: {
                Id: 300000,
                Name: "Selecteer je module",
                Description: "Selecteer je module",
            },
            locked: false,
            startDate: `2027-10-07T00:00:00Z`,
        },
        {
            Id: 600000,
            Year: 4,
            semester: 1,
            Module: {
                Id: 200000,
                Name: "Selecteer je module",
                description: "Selecteer je module",
            },
            locked: false,
            Description: `2027-01-01T00:00:00Z`,
        },
        {
            Id: 500000,
            Year: 4,
            semester: 2,
            Module: {
                Id: 300000,
                Name: "Selecteer je module",
                Description: "Selecteer je module",
            },
            locked: false,
            startDate: `2027-10-07T00:00:00Z`,
        },
    ],
};