services:
  api:
    build:
      context: ./LOM.API
      dockerfile: Dockerfile
    container_name: lom-api
    restart: unless-stopped
    ports:
      - "8001:8080"
  client:
    depends_on:
      - api
    build:
      context: ./LOM.Client
      dockerfile: Dockerfile
    container_name: lom-client
    restart: unless-stopped
    ports:
      - "8002:3000"